# Generated by Django 3.2.7 on 2021-09-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dumpster', '0003_modelasset_textasset_textureasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='textasset',
            name='syntax_highlighting_language',
            field=models.CharField(blank=True, help_text='Uses Prism.js to render. Refer to https://prismjs.com/#supported-languages for the value for this box', max_length=100),
        ),
    ]
