# Generated by Django 3.2.7 on 2021-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dumpster', '0005_auto_20210915_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelasset',
            name='preview_model',
            field=models.FileField(blank=True, upload_to='assets/preview_model/'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='file',
            field=models.ImageField(upload_to='assets/images/'),
        ),
    ]
