# Generated by Django 3.2.7 on 2021-09-17 02:31

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dumpster', '0007_auto_20210916_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('text_color', colorfield.fields.ColorField(blank=True, default='', max_length=18)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='', max_length=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(to='Dumpster.Tag'),
        ),
    ]
