# Generated by Django 3.2.7 on 2021-09-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dumpster', '0008_auto_20210916_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Dumpster.Tag'),
        ),
    ]
